site_name: GL.iNet Docs
repo_url: https://github.com/domino-team/docs/
site_description: This is the documentation site for GL.iNet OpenWrt Wi-Fi products
site_favicon: favicon.png
copyright: <a href='https://gl-inet.com/'> GL Technologies</a> 2018
google_analytics: null
site_dir: '/var/www/newdocs'
#site_dir: 'site'
docs_dir: 'docs'
theme_dir: 'gl_theme'
#theme: 'mkdocs'
include_next_prev: false

pages:
- Home: 
    - 'Home' : 'index.md'
    - 'About Us' : 'about.md'
    - 'Services' : 'service.md'
- Hardware:
    - 'GL.iNet6416' : 'hardware/6416spec.md'
    - 'GL-AR150 Series' : 'hardware/ar150spec.md'
    - 'GL-AR300M Series' : 'hardware/ar300mspec.md'
    - 'GL-MT300A' : 'hardware/mt300aspec.md'
    - 'GL-MT300N' : 'hardware/mt300nspec.md'
    - 'GL-MT300N-V2' : 'hardware/mt300n-v2spec.md'
    - 'GL-AR750 Series' : 'hardware/ar750spec.md'
    - 'GL-MiFi Series' : 'hardware/mifispec.md'
    - 'GL-USB150 Series' : 'hardware/usb150spec.md'
    - 'GL-B1300' : 'hardware/b1300spec.md'
    - 'Domino Kit' : 'domino/index.md'    
- 'Setup':
  - 'First-time Setup' : 'mini/index.md'
  - 'Internet Settings, MAC Clone, DNS' : 'mini/internet.md'
  - 'Repeater Manager' : 'mini/repeater_manager.md'
  - '3G/4G Modem and Smartphone Tethering' : 'setup/3g4g.md'
  - 'LAN IP' : 'setup/lan.md'
  - 'Wi-Fi Settings (AP)': 'setup/wifi.md'
  - 'Firmware Upgrading' : 'mini/firmware.md'
  - 'Momdem Manager' : 'setup/mifi.md'
  - 'Firewall' : 'setup/firewall.md'
- Development:
    - 'Working with UART serial' : 'diy/serial.md'
    - 'working with uboot' : 'diy/uboot.md'
- Application:
    - 'OpenVPN' : 'openwrt/openvpn.md'
    - 'Tor' : 'openwrt/tor.md'
    - 'EasyTether' : 'openwrt/tether.md'
    - 'Shadowsocks' : 'app/shadowsocks.md'
    - 'WireGuard' : 'app/wireguard.md'        
- Video:
    - 'Product Intro' : 'video/product.md'   
    - 'Tutorial' : 'video/tutor.md'
    - 'Customer Review' : 'video/review.md'
    - 'Case Study' : 'video/case.md'   
- Troubleshooting:
    - 'LED Indicator' : 'diy/serial.md'
    - 'Factory Reset' : 'diy/serial.md'
    - 'UART Serial' : 'diy/serial.md'
    - 'Debrick via Uboot' : 'diy/uboot.md'

- 'Domino Kit' :
  - 'Getting Started' : 'domino/index.md'
  - 'Domore Core' : 'domino/hardware/core.md'
  - 'Domino Pi Baseboard': 'domino/pi/pi.md'
  - 'Domino Pi - Single Eth board': 'domino/pi/single_eth.md'
  - 'Domino Pi - Due Eth board': 'domino/pi/dual_eth.md'
  - 'Domino Pi - Signle USB board': 'domino/pi/single_usb.md'
  - 'Domino Pi - 3xUSB+MicroSD combo': 'domino/pi/usb_combo.md'
  - 'Domino Pi - I2S board': 'domino/pi/i2s.md'
  - 'Domino Pi - SPI/JTAG': 'domino/pi/spi_jtag.md'
  - 'Domino Pi - LED': 'domino/pi/led.md'
  - 'Domino Qi Mini' : 'domino/qi/mini.md'
  - 'Domino Qi baseboard': 'domino/qi/base.md'
  - 'Pi: Using the firmware': 'domino/pi/using.md'
  - 'Pi: Compile firmware': 'domino/pi/compile.md'
  - 'Pi: Flashing and debricking': 'domino/pi/flashing.md'
  - 'Pi: Playing Music': 'domino/pi/audio.md'
  - 'Pi: Working with Serial': 'domino/pi/serial.md'
  - 'Pi: Debricking using SPI/JTAG board': 'domino/pi/spi.md'
  - 'Qi: Getting Started': 'domino/qi/index.md'
  - 'Qi: Using Arduino or Linino Firmware': 'domino/qi/arduino-yun.md'
  - 'Qi: Using NodeJS and LininoIO': 'domino/qi/nodejs.md'
  - 'Qi: Using Serial': 'domino/qi/serial.md'


